apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flex-envoy
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Values.prometheusReleaseLabel }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Values.flex.namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.flex.serviceLabel }}
  endpoints:
    - port: {{ .Values.flex.promStatsPort }}
      path: {{ .Values.flex.scrapePath }}
      interval: {{ .Values.flex.scrapeInterval }}
