UpdateOrgLevelSettings:
  value:
    deletionSettings:
      hardDeletionEnabled: true
      assetRoleAssignmentSettings: true

FetchOrgLevelSettings:
  value:
    - deletionSettings:
        hardDeletionEnabled: true
        assetRoleAssignmentSettings: true
